### ISSUE TITLE
"mulle_vararg_make_builderbuffer" is not defined

### ISSUE THREAD

**Issue by 1170300604** [mulle-c/mulle-vararg#3]
I try to run the simple of doc Mulle-vararg-builder API, and I don't find any definition of "mulle_vararg_make_builderbuffer" ,  only "mulle_vararg_list_make", are they work the same ?

**Comment by mulle-nat** [comment]
Sorry for the late reply. It may be that the documentation is neglected .  I think its probably easiest to look at one of the builder tests like [double-pain.c](https://github.com/mulle-c/mulle-vararg/blob/release/test/builder/double-pain.c) and see how its done.

One caveat still applies, you can't use this to build <stdarg.h> argument lists. Just so you don't run into a dead end here :)
